import type { CommandCatalog } from "./types.js";

export const COMMAND_CATALOG: CommandCatalog = {
  appName: "swarmhq",
  pageTitle: "swarmhq Control Room",
  groups: [
    {
      id: "observability",
      label: "Observability",
      description: "Health and status commands for safe read-only inspection.",
    },
    {
      id: "configuration",
      label: "Configuration",
      description: "Locate, inspect, and seed local config files.",
    },
    {
      id: "operations",
      label: "Operations",
      description: "Inspect the live swarm through the local CLI bridge.",
    },
    {
      id: "maintenance",
      label: "Maintenance",
      description: "Controlled cluster changes such as reboot and leadership movement.",
    },
    {
      id: "security",
      label: "Security",
      description: "Preview how secrets and infrastructure data are redacted.",
    },
  ],
  picklists: [
    {
      id: "output-format",
      label: "Output Format",
      options: [
        {
          value: "summary",
          label: "Summary",
          description: "Compact human-readable output.",
        },
        {
          value: "json",
          label: "JSON",
          description: "Structured machine-readable payload.",
        },
      ],
    },
    {
      id: "health-output-format",
      label: "Health Output",
      options: [
        {
          value: "summary",
          label: "Summary",
          description: "Quick health check output.",
        },
        {
          value: "detailed",
          label: "Detailed",
          description: "Expanded node, keepalived, and service status.",
        },
        {
          value: "json",
          label: "JSON",
          description: "Structured machine-readable payload.",
        },
      ],
    },
    {
      id: "host-key-mode",
      label: "SSH Host Key Checking",
      options: [
        {
          value: "strict",
          label: "Strict",
          description: "Require known hosts before connection.",
        },
        {
          value: "accept-new",
          label: "Accept New",
          description: "Trust first-seen hosts only.",
        },
        {
          value: "insecure",
          label: "Insecure",
          description: "Disable host key checking. Use only for demos.",
        },
      ],
    },
    {
      id: "redaction-source",
      label: "Preview Source",
      options: [
        {
          value: "config",
          label: "Config JSON",
          description: "Render the active config as redacted JSON.",
        },
        {
          value: "env",
          label: "Env Sample",
          description: "Render a sample env block with secrets masked.",
        },
        {
          value: "custom",
          label: "Custom Text",
          description: "Redact the text you provide below.",
        },
      ],
    },
    {
      id: "docker-output-format",
      label: "Docker Output Format",
      options: [
        {
          value: "summary",
          label: "Summary",
          description: "Compact tabular text from the CLI.",
        },
        {
          value: "json",
          label: "JSON",
          description: "Structured JSON emitted by the CLI.",
        },
      ],
    },
    {
      id: "node-update-mode",
      label: "Node Update Mode",
      options: [
        {
          value: "all",
          label: "OS + Docker",
          description: "Apply operating system and Docker package updates.",
        },
        {
          value: "os",
          label: "OS Only",
          description: "Apply operating system package updates only.",
        },
        {
          value: "docker",
          label: "Docker Only",
          description: "Apply Docker engine and related package updates only.",
        },
      ],
    },
    {
      id: "cluster-nodes",
      label: "Cluster Nodes",
      options: [],
    },
    {
      id: "cluster-services",
      label: "Cluster Services",
      options: [],
    },
    {
      id: "content-source",
      label: "Content Source",
      options: [
        { value: "file", label: "File Path", description: "Read content from a path on the CLI host or leader node." },
        { value: "stdin", label: "Text", description: "Send textarea content through stdin." },
      ],
    },
  ],
  commands: [
    {
      id: "health.report",
      label: "Health Report",
      summary: "Run SSH-backed health checks against the configured swarm cluster.",
      groupId: "observability",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose quick, detailed, or JSON output.",
          kind: "picklist",
          picklistId: "health-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "config.show",
      label: "Show Config",
      summary: "Display the active config path and parsed config payload.",
      groupId: "configuration",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "output-format",
          defaultValue: "json",
        },
      ],
    },
    {
      id: "config.path",
      label: "Resolve Config Path",
      summary: "Show the resolved config path without loading the file.",
      groupId: "configuration",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
      ],
    },
    {
      id: "config.init",
      label: "Seed Example Config",
      summary: "Write an example config file using safe defaults.",
      groupId: "configuration",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Where to write the example config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "clusterName",
          label: "Cluster Name",
          description: "Friendly cluster identifier for the example config.",
          kind: "text",
          defaultValue: "example-swarm",
        },
        {
          id: "vip",
          label: "VIP",
          description: "Safe example virtual IP address.",
          kind: "text",
          defaultValue: "198.51.100.10",
        },
        {
          id: "sshMode",
          label: "SSH Host Key Checking",
          description: "Initial SSH trust mode for the example config.",
          kind: "picklist",
          picklistId: "host-key-mode",
          defaultValue: "accept-new",
        },
        {
          id: "hideIps",
          label: "Hide IPs",
          description: "Enable IP redaction in the example config.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "force",
          label: "Overwrite Existing File",
          description: "Replace the target file if it already exists.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "security.redaction-preview",
      label: "Redaction Preview",
      summary: "Preview how the CLI masks secrets and IP data.",
      groupId: "security",
      options: [
        {
          id: "source",
          label: "Preview Source",
          description: "Choose which input should be redacted.",
          kind: "picklist",
          picklistId: "redaction-source",
          defaultValue: "config",
        },
        {
          id: "customText",
          label: "Custom Text",
          description: "Used only when Preview Source is set to Custom Text.",
          kind: "textarea",
          placeholder: "SWARM_VRRP_PASSWORD=super-secret",
        },
        {
          id: "hideIps",
          label: "Hide IPs",
          description: "Redact IPv4 addresses in addition to secrets.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "operations.nodes",
      label: "List Nodes",
      summary: "Inspect the current swarm node roster over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        {
          id: "context",
          label: "Docker Context",
          description: "Optional local Docker context. Leave blank to use the configured SSH swarm nodes.",
          kind: "text",
          placeholder: "production-swarm",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "docker-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "operations.services",
      label: "List Services",
      summary: "Inspect swarm services over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        {
          id: "context",
          label: "Docker Context",
          description: "Optional local Docker context. Leave blank to use the configured SSH swarm nodes.",
          kind: "text",
          placeholder: "production-swarm",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "docker-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "operations.service-inspect",
      label: "Inspect Service",
      summary: "Show details for a specific swarm service over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        {
          id: "context",
          label: "Docker Context",
          description: "Optional local Docker context. Leave blank to use the configured SSH swarm nodes.",
          kind: "text",
          placeholder: "production-swarm",
        },
        {
          id: "serviceName",
          label: "Service Name",
          description: "Required service name to inspect.",
          kind: "text",
          placeholder: "traefik",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "docker-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "operations.service-tasks",
      label: "Service Tasks",
      summary: "List task history for a specific swarm service over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        {
          id: "context",
          label: "Docker Context",
          description: "Optional local Docker context. Leave blank to use the configured SSH swarm nodes.",
          kind: "text",
          placeholder: "production-swarm",
        },
        {
          id: "serviceName",
          label: "Service Name",
          description: "Required service name to inspect.",
          kind: "text",
          placeholder: "traefik",
        },
        {
          id: "all",
          label: "Show All Tasks",
          description: "Include non-running task history in the Docker query.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "docker-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "operations.leader",
      label: "Leader Status",
      summary: "Show the current swarm leader over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        {
          id: "context",
          label: "Docker Context",
          description: "Optional local Docker context. Leave blank to use the configured SSH swarm nodes.",
          kind: "text",
          placeholder: "production-swarm",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "docker-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "operations.ps",
      label: "Task Listing",
      summary: "List task placements per node over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        {
          id: "context",
          label: "Docker Context",
          description: "Optional local Docker context. Leave blank to use the configured SSH swarm nodes.",
          kind: "text",
          placeholder: "production-swarm",
        },
        {
          id: "node",
          label: "Node",
          description: "Optional node hostname. When omitted, tasks are grouped across all nodes.",
          kind: "text",
          placeholder: "manager-a",
        },
        {
          id: "all",
          label: "Show All Tasks",
          description: "Include non-running task history in the Docker query.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "docker-output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "maintenance.leader-switch",
      label: "Switch Leader",
      summary: "Move the VIP and/or swarm leadership to a specific manager node.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "target",
          label: "Target Node",
          description: "Manager hostname or IP that should receive the VIP or leadership.",
          kind: "text",
          placeholder: "docker",
          required: true,
        },
        {
          id: "vipOnly",
          label: "VIP Only",
          description: "Only move keepalived VIP ownership.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "swarmOnly",
          label: "Swarm Only",
          description: "Only trigger swarm leadership movement.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "strictTarget",
          label: "Strict Target",
          description: "Temporarily demote other managers so the target becomes leader.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "dryRun",
          label: "Dry Run",
          description: "Print the execution plan without making any changes.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "confirm",
          label: "Confirm Destructive Action",
          description: "Required before a maintenance command will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "maintenance.reboot-list",
      label: "List Reboot Targets",
      summary: "Show configured nodes with their current reboot safety status.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
      ],
    },
    {
      id: "maintenance.reboot-node",
      label: "Reboot Node",
      summary: "Drain, reboot, and optionally restore one configured node.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "target",
          label: "Target Node",
          description: "Node hostname or IP to reboot.",
          kind: "text",
          placeholder: "docker1",
          required: true,
        },
        {
          id: "drainWait",
          label: "Drain Wait (seconds)",
          description: "How long to wait after drain before reboot.",
          kind: "text",
          defaultValue: "30",
        },
        {
          id: "bootWait",
          label: "Boot Wait (seconds)",
          description: "Maximum wait for the node to come back online.",
          kind: "text",
          defaultValue: "300",
        },
        {
          id: "force",
          label: "Force Reboot",
          description: "Skip drain and reboot immediately.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "noRestore",
          label: "No Restore",
          description: "Leave the node drained after reboot.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "dryRun",
          label: "Dry Run",
          description: "Print the execution plan without making any changes.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "confirm",
          label: "Confirm Destructive Action",
          description: "Required before a maintenance command will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "maintenance.reboot-status",
      label: "Reboot Status",
      summary: "Check whether a node is back online, on SSH, and active in swarm.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "target",
          label: "Target Node",
          description: "Node hostname or IP to inspect.",
          kind: "text",
          placeholder: "docker1",
          required: true,
        },
      ],
    },
    {
      id: "maintenance.update-check",
      label: "Scan Node Updates",
      summary: "Check OS and Docker update posture for one node or the whole cluster.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "target",
          label: "Target Node",
          description: "Optional node hostname or IP. Leave blank to scan all configured nodes.",
          kind: "text",
          placeholder: "docker1",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "maintenance.update-node",
      label: "Update Node",
      summary: "Apply OS and/or Docker package updates to one configured node.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "target",
          label: "Target Node",
          description: "Node to update.",
          kind: "picklist",
          picklistId: "cluster-nodes",
          required: true,
        },
        {
          id: "mode",
          label: "Update Mode",
          description: "Choose which package set should be updated.",
          kind: "picklist",
          picklistId: "node-update-mode",
          defaultValue: "all",
        },
        {
          id: "skipReboot",
          label: "Skip Reboot",
          description: "Do not run the controlled reboot flow even if the node requires one.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "dryRun",
          label: "Dry Run",
          description: "Print the execution plan without making any changes.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "confirm",
          label: "Confirm Destructive Action",
          description: "Required before a maintenance command will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "maintenance.update-all",
      label: "Update All Nodes",
      summary: "Apply OS and/or Docker updates across the configured cluster sequentially.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "mode",
          label: "Update Mode",
          description: "Choose which package set should be updated.",
          kind: "picklist",
          picklistId: "node-update-mode",
          defaultValue: "all",
        },
        {
          id: "exclude",
          label: "Exclude Nodes",
          description: "Comma-separated node ids or hosts to skip.",
          kind: "text",
          placeholder: "docker1,192.168.1.20",
        },
        {
          id: "skipReboot",
          label: "Skip Reboot",
          description: "Do not run the controlled reboot flow even if a node requires one.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "dryRun",
          label: "Dry Run",
          description: "Print the execution plan without making any changes.",
          kind: "checkbox",
          defaultValue: false,
        },
        {
          id: "confirm",
          label: "Confirm Destructive Action",
          description: "Required before a maintenance command will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "operations.service-update-scan",
      label: "Scan Service Image Updates",
      summary: "Compare deployed swarm service image digests with the latest pullable image digest.",
      groupId: "operations",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "maintenance.service-update",
      label: "Update Service Image",
      summary: "Pull the latest image and roll a specific swarm service.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "serviceName",
          label: "Service Name",
          description: "Required swarm service to update.",
          kind: "picklist",
          picklistId: "cluster-services",
          required: true,
        },
        {
          id: "confirm",
          label: "Confirm Destructive Action",
          description: "Required before a maintenance command will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "operations.container-update-scan",
      label: "Scan Container Updates",
      summary: "Inspect running containers and show whether they can be updated through a supported path.",
      groupId: "operations",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "format",
          label: "Format",
          description: "Choose CLI-style summary or JSON output.",
          kind: "picklist",
          picklistId: "output-format",
          defaultValue: "summary",
        },
      ],
    },
    {
      id: "operations.stack-list",
      label: "List Stacks",
      summary: "List deployed swarm stacks over SSH, or use a local Docker context when provided.",
      groupId: "operations",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "operations.stack-ps",
      label: "Stack Tasks",
      summary: "List task placement and state for a stack.",
      groupId: "operations",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "stackName", label: "Stack Name", description: "Stack to inspect.", kind: "text", placeholder: "apps", required: true },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "operations.stack-services",
      label: "Stack Services",
      summary: "List services in a stack.",
      groupId: "operations",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "stackName", label: "Stack Name", description: "Stack to inspect.", kind: "text", placeholder: "apps", required: true },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "operations.network-list",
      label: "List Networks",
      summary: "List Docker networks.",
      groupId: "operations",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "operations.network-inspect",
      label: "Inspect Network",
      summary: "Inspect Docker network metadata.",
      groupId: "operations",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "networkName", label: "Network Name", description: "Network to inspect.", kind: "text", placeholder: "ingress", required: true },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "operations.logs",
      label: "Service Logs",
      summary: "Read or follow swarm service logs.",
      groupId: "operations",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "serviceName", label: "Service Name", description: "Service to read logs from.", kind: "picklist", picklistId: "cluster-services", required: true },
        { id: "follow", label: "Follow", description: "Stream logs until stopped.", kind: "checkbox", defaultValue: false },
        { id: "since", label: "Since", description: "Docker duration or timestamp.", kind: "text", placeholder: "1h" },
        { id: "tail", label: "Tail", description: "Number of lines from the end.", kind: "text", placeholder: "100" },
      ],
    },
    {
      id: "maintenance.container-update",
      label: "Update Container",
      summary: "Update one supported container by routing it through its owning swarm service.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "containerName",
          label: "Container Name",
          description: "Required running container name or ID.",
          kind: "text",
          placeholder: "caddy_caddy.1.abcd1234",
          required: true,
        },
        {
          id: "confirm",
          label: "Confirm Destructive Action",
          description: "Required before a maintenance command will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "maintenance.stack-deploy",
      label: "Deploy Stack",
      summary: "Deploy a compose file as a swarm stack.",
      groupId: "maintenance",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "filePath", label: "Compose File", description: "Path to the compose file.", kind: "text", placeholder: "/srv/apps/compose.yml", required: true },
        { id: "stackName", label: "Stack Name", description: "Stack name to deploy.", kind: "text", placeholder: "apps", required: true },
        { id: "confirm", label: "Confirm", description: "Required before deploy will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "maintenance.stack-remove",
      label: "Remove Stack",
      summary: "Remove a deployed swarm stack.",
      groupId: "maintenance",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "stackName", label: "Stack Name", description: "Stack to remove.", kind: "text", placeholder: "apps", required: true },
        { id: "confirm", label: "Confirm", description: "Required before removal will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "maintenance.network-create",
      label: "Create Network",
      summary: "Create an attachable overlay network.",
      groupId: "maintenance",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "networkName", label: "Network Name", description: "Network to create.", kind: "text", placeholder: "app_net", required: true },
        { id: "driver", label: "Driver", description: "Docker network driver.", kind: "text", defaultValue: "overlay" },
        { id: "confirm", label: "Confirm", description: "Required before creation will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "maintenance.network-remove",
      label: "Remove Network",
      summary: "Remove a Docker network.",
      groupId: "maintenance",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "networkName", label: "Network Name", description: "Network to remove.", kind: "text", placeholder: "app_net", required: true },
        { id: "confirm", label: "Confirm", description: "Required before removal will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "maintenance.node-label-add",
      label: "Add Node Label",
      summary: "Add or update a Docker node label.",
      groupId: "maintenance",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "nodeId", label: "Node", description: "Node to label.", kind: "picklist", picklistId: "cluster-nodes", required: true },
        { id: "labelKey", label: "Key", description: "Label key.", kind: "text", placeholder: "zone", required: true },
        { id: "labelValue", label: "Value", description: "Optional label value.", kind: "text", placeholder: "east" },
        { id: "confirm", label: "Confirm", description: "Required before label update will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "maintenance.node-label-remove",
      label: "Remove Node Label",
      summary: "Remove a Docker node label.",
      groupId: "maintenance",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "nodeId", label: "Node", description: "Node to update.", kind: "picklist", picklistId: "cluster-nodes", required: true },
        { id: "labelKey", label: "Key", description: "Label key to remove.", kind: "text", placeholder: "zone", required: true },
        { id: "confirm", label: "Confirm", description: "Required before label update will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "maintenance.node-promote",
      label: "Promote Node to Manager",
      summary: "Promote a worker node to swarm manager role.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "nodeId",
          label: "Node",
          description: "Node to promote to manager.",
          kind: "picklist",
          picklistId: "cluster-nodes",
          required: true,
        },
        {
          id: "confirm",
          label: "Confirm",
          description: "Required before the promotion will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "maintenance.node-demote",
      label: "Demote Manager to Worker",
      summary: "Demote a manager node to worker role. Ensure quorum is maintained.",
      groupId: "maintenance",
      options: [
        {
          id: "configPath",
          label: "Config Path",
          description: "Optional override for the active config file.",
          kind: "text",
          placeholder: "/absolute/path/to/config.json",
        },
        {
          id: "nodeId",
          label: "Node",
          description: "Manager node to demote to worker.",
          kind: "picklist",
          picklistId: "cluster-nodes",
          required: true,
        },
        {
          id: "confirm",
          label: "Confirm",
          description: "Required before the demotion will run.",
          kind: "checkbox",
          defaultValue: false,
        },
      ],
    },
    {
      id: "security.secret-create",
      label: "Create Secret",
      summary: "Create a Docker secret from a file path or textarea content. Content is not stored in activity.",
      groupId: "security",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "name", label: "Name", description: "Secret name.", kind: "text", placeholder: "api_token", required: true },
        { id: "contentSource", label: "Source", description: "Read content from a path or textarea.", kind: "picklist", picklistId: "content-source", defaultValue: "file" },
        { id: "filePath", label: "File Path", description: "Secret file path.", kind: "text", placeholder: "/run/secrets/api_token" },
        { id: "stdinContent", label: "Secret Content", description: "Secret content sent through stdin and omitted from activity values.", kind: "textarea" },
        { id: "confirm", label: "Confirm", description: "Required before creation will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "security.secret-list",
      label: "List Secrets",
      summary: "List Docker secret metadata.",
      groupId: "security",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "security.secret-inspect",
      label: "Inspect Secret",
      summary: "Inspect Docker secret metadata without exposing secret content.",
      groupId: "security",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "name", label: "Name", description: "Secret name.", kind: "text", placeholder: "api_token", required: true },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "security.secret-remove",
      label: "Remove Secret",
      summary: "Remove a Docker secret.",
      groupId: "security",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "name", label: "Name", description: "Secret name.", kind: "text", placeholder: "api_token", required: true },
        { id: "confirm", label: "Confirm", description: "Required before removal will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "security.config-create",
      label: "Create Docker Config",
      summary: "Create a Docker config from a file path or textarea content. Content is not stored in activity.",
      groupId: "security",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "name", label: "Name", description: "Docker config name.", kind: "text", placeholder: "app_config", required: true },
        { id: "contentSource", label: "Source", description: "Read content from a path or textarea.", kind: "picklist", picklistId: "content-source", defaultValue: "file" },
        { id: "filePath", label: "File Path", description: "Config file path.", kind: "text", placeholder: "/srv/app.conf" },
        { id: "stdinContent", label: "Config Content", description: "Config content sent through stdin and omitted from activity values.", kind: "textarea" },
        { id: "confirm", label: "Confirm", description: "Required before creation will run.", kind: "checkbox", defaultValue: false },
      ],
    },
    {
      id: "security.config-list",
      label: "List Docker Configs",
      summary: "List Docker Swarm config metadata.",
      groupId: "security",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "security.config-inspect",
      label: "Inspect Docker Config",
      summary: "Inspect Docker config metadata.",
      groupId: "security",
      options: [
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "name", label: "Name", description: "Docker config name.", kind: "text", placeholder: "app_config", required: true },
        { id: "format", label: "Format", description: "Choose CLI-style summary or JSON output.", kind: "picklist", picklistId: "docker-output-format", defaultValue: "summary" },
      ],
    },
    {
      id: "security.config-remove",
      label: "Remove Docker Config",
      summary: "Remove a Docker config.",
      groupId: "security",
      options: [
        { id: "configPath", label: "Config Path", description: "Optional override for the active config file.", kind: "text", placeholder: "/absolute/path/to/config.json" },
        { id: "context", label: "Docker Context", description: "Optional local Docker context.", kind: "text", placeholder: "production-swarm" },
        { id: "name", label: "Name", description: "Docker config name.", kind: "text", placeholder: "app_config", required: true },
        { id: "confirm", label: "Confirm", description: "Required before removal will run.", kind: "checkbox", defaultValue: false },
      ],
    },
  ],
};
